# Generated by Django 5.2.11 on 2026-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('event_type', models.CharField(choices=[('olympiad', 'Олимпиада'), ('competition', 'Конкурс')], max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('upcoming', 'Предстоящее'), ('active', 'Активное'), ('completed', 'Завершённое'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Очно'), ('hybrid', 'Смешанный')], default='online', max_length=20, verbose_name='Формат')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('registration_deadline', models.DateField(verbose_name='Дедлайн регистрации')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. участников')),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мин. возраст')),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Макс. возраст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('active', 'Участвует'), ('completed', 'Завершил'), ('withdrawn', 'Отказался')], default='registered', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс (%)')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Назначение жюри',
                'verbose_name_plural': 'Назначения жюри',
            },
        ),
    ]
