# Generated by Django 6.0.3 on 2026-03-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventstage_eventtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/', verbose_name='Файл задания'),
        ),
    ]
