# Generated by Django 6.0.3 on 2026-03-25 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtask_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_application',
            field=models.BooleanField(default=False, help_text='Участник должен загрузить заявку/анкету для завершения регистрации', verbose_name='Требовать заявку на участие'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_parental_consent',
            field=models.BooleanField(default=False, help_text='Если включено — согласие родителей нужно всем, не только несовершеннолетним', verbose_name='Требовать согласие родителей (для всех)'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending_docs', 'Ожидает документы'), ('registered', 'Зарегистрирован'), ('active', 'Участвует'), ('completed', 'Завершил'), ('withdrawn', 'Отказался')], default='registered', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('parental_consent', 'Согласие родителей'), ('application', 'Заявка на участие'), ('other', 'Прочее')], default='parental_consent', max_length=30, verbose_name='Тип документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='registration_docs/', verbose_name='Файл документа')),
                ('parent_full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО родителя/законного представителя')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание участника')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус проверки')),
                ('admin_note', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.eventregistration', verbose_name='Регистрация')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Документ регистрации',
                'verbose_name_plural': 'Документы регистрации',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
