# Generated by Django 5.2.11 on 2026-03-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_requires_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sequential_stages',
            field=models.BooleanField(default=False, help_text='Участник видит следующий этап только после сдачи работы на предыдущем и в рамках дат этапа', verbose_name='Последовательный доступ к этапам'),
        ),
    ]
