# Generated by Django 5.2.11 on 2026-02-24 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Балл')),
                ('feedback', models.TextField(blank=True, verbose_name='Комментарий жюри')),
                ('criteria_completeness', models.BooleanField(default=False, verbose_name='Полнота ответа')),
                ('criteria_accuracy', models.BooleanField(default=False, verbose_name='Точность данных')),
                ('criteria_examples', models.BooleanField(default=False, verbose_name='Примеры и иллюстрации')),
                ('criteria_grammar', models.BooleanField(default=False, verbose_name='Грамотность изложения')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(choices=[(1, '1 место'), (2, '2 место'), (3, '3 место'), (0, 'Участник')], verbose_name='Место')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Итоговый балл')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Сертификат выдан')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['place', '-final_score'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/', verbose_name='Файл работы')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байты)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('under_review', 'На проверке'), ('evaluated', 'Оценена')], default='draft', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
