# Generated by Django 5.2.11 on 2026-02-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Жюри'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='submission',
            name='jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Назначенное жюри'),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='submissions.submission', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='submissions.submission', verbose_name='Работа'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('event', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together={('event', 'participant')},
        ),
    ]
