# Generated by Django 5.2.11 on 2026-03-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_sequential_stages_and_stage_submission'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='events.eventstage', verbose_name='Этап'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('event', 'stage', 'participant')},
        ),
    ]
