# Generated by Django 5.2.11 on 2026-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер (байты)')),
                ('doc_type', models.CharField(choices=[('regulation', 'Положение'), ('privacy', 'Политика конфиденциальности'), ('methodology', 'Методические материалы'), ('template', 'Шаблон работы'), ('criteria', 'Критерии оценивания'), ('other', 'Прочее')], max_length=20, verbose_name='Тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Скачиваний')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
